// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3J0Xav9Fm2wcSzdnylhl70r00lSQvvMg',
    appId: '1:589131812593:web:198ecdc434b919754a2350',
    messagingSenderId: '589131812593',
    projectId: 'familytrackerapp-44ca2',
    authDomain: 'familytrackerapp-44ca2.firebaseapp.com',
    storageBucket: 'familytrackerapp-44ca2.firebasestorage.app',
    measurementId: 'G-2FVLTNRG0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQMOecoidAWnZeUJCku8IsW_M92kAfBU',
    appId: '1:589131812593:android:2623e6dabc3f7d344a2350',
    messagingSenderId: '589131812593',
    projectId: 'familytrackerapp-44ca2',
    storageBucket: 'familytrackerapp-44ca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Qh6rngozwvlgEzcQ5dNbZa-sgG9a33A',
    appId: '1:589131812593:ios:29793b34cc147d554a2350',
    messagingSenderId: '589131812593',
    projectId: 'familytrackerapp-44ca2',
    storageBucket: 'familytrackerapp-44ca2.firebasestorage.app',
    iosBundleId: 'com.example.familytrackapp',
  );
}
